[phases.setup]
nixPkgs = ["python311", "python311Packages.flask"]

[phases.install]
cmds = [
  "python -c 'import urllib.request; urllib.request.urlretrieve(\"https://raw.githubusercontent.com/pallets/flask/main/requirements.txt\", \"requirements.txt\")'",
  "python -m pip install --user flask-cors"
]

[phases.start]
cmd = "python backend/app.py"
