[phases.setup]
nixPkgs = ["python311", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv --system-site-packages venv",
  "./venv/bin/pip install --break-system-packages -r backend/requirements.txt"
]

[phases.start]
cmd = "./venv/bin/python backend/app.py"
