services:
  - type: web
    name: torneo-futbol-juvenil
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000
